# Generated by Django 4.2.2 on 2023-06-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='capteurs',
            fields=[
                ('IDs', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nom_capteur', models.CharField(max_length=255, unique=True)),
                ('piece', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'capteurs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='donnees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('degre', models.FloatField()),
            ],
            options={
                'db_table': 'donnees',
                'managed': False,
            },
        ),
    ]
